general:
  title: "[K97] MEDIA"
  email: your-email@example.com
  description: >- # this means to ignore newlines until "baseurl:"
    شوێنێک تاکو پێکەوە فێری پڕۆگرامسازی ببین، وە سەرچاوەی کوردی لە بوارەکە دەوڵەمەندتر بکەین
  baseurl: "/"
  url: ""
  favicon: images/favicon.svg

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compresed

defaults:
  - scope:
      path: "topics"
    values:
      layout: "topic-page"
      permalink: "/topic/"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
